spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test_portal?currentSchema=test_portal
    username: root
    password: root
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    create-schemas: true
    enabled: true
    locations: classpath:/db/data_migration,classpath:/db/ddl_migration

exam:
  portal:
    front-url: http://localhost:4200/
    image-upload-directory: src/main/resources/images/profile
    image-default: default.png
    jwt-header: Authorization
    jwt-secret: secret4356789654324567865432567854324567854fsdfdsfdsfdsdfsfdfdswqeq21wasdsaadsdagfderew2rgf
    jwt-expiration: 60480033


